### ISSUE TITLE
PGwire round #2

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2170]
To be converted to individual cards as required - for now just a to-do list:

- [x] DML (empty db is pretty boring!)
- [x] xtdb/xtdb#2204 
- [ ] correct implicit transaction semantics as-per-spec (e.g SET TRANSACTION state used for queries outside of BEGIN COMMIT)
- [ ] multiple statement support
- [x] test suites for common pg client libs
- [ ] xtdb/xtdb#2205 
- [x] cancellation support
- [ ] batch param tests (DML)
- [ ] error codes and messages pass
- [x] server parameter pass (ensure our defaults are correct - and might they need to be customised?)
- [x] session parameter pass (should we have behavior for settings, should they be thrown away? error? notice?)

later:

- [ ] correct portal flow with limit support
- [ ] streaming queries
- [ ] read api that returns arrow internally to better clarify mappings
- [ ] limits hardening (memory, msg sizes) (e.g try not to JVM OOM!)
- [ ] concurrency hardening, tests, max buf on tp
- [ ] binary formatting - clients are able to specify a 'binary mode'
- [ ] COPY commands
- [x] jsonb option
- [ ] string parameter sniff (allow json round trip?)
- [ ] conn mgmt (stat / kill)?
- [ ] node mgmt (stat / restart)?
- [x] remove canned / string hacks and be able to customize a pg-ish parser on top of the core2 sql grammar.

**Comment by jarohen** [comment]
this one's gone pretty stale, closing
