### ISSUE TITLE
pgwire error messages

### ISSUE THREAD

**Issue by deobald** [xtdb/crux#2197]
**Please add your error / repro as a _comment_ and notify @deobald that you would like this description edited. Do not edit this description yourself.** 🙏 

# Triage:

* [x] Double Quotes produce a strange error: `steven=> INSERT INTO people (id, name) VALUES (1, "Floh");` results in `
XTDB requires fully-qualified columns`
* [x] ERROR: DML is unsupported in a READ ONLY transaction -- would be nice if this error multi-lines an explanation of how to get around it
* [x] unqualified DML should warn the user: `update users set name='deo' where id=1234;` causes `Assert failed: ["XTDB requires fully-qualified columns: id at line 1, column 35"]` but the client isn't notified.
* [x] the server should recover from failed commits (`server closed the connection unexpectedly`) — this currently happens when user submits and unqualified `update`, for example, but the server should recover from this sort of exception even if unqualified DML is prevented. The cause is that the erroneous DML is still on the log when future commits are attempted. Solution is this issue: https://github.com/xtdb/xtdb/issues/2221
* [x] `select *` error is opaque: `=> select * from users;` => `ERROR:  unexpected server error during query execution`

**Comment by deobald** [comment]
* [x] unqualified query: `select name from users;` closes connection
* [x] `insert into users (id, name, created_at) values (2, 'jdt', '2022-08-12 00:00:00'); insert into users (id, name, created_at) values (2, 'jdt', TIMESTAMP '2022-08-12 00:00:00');` -- DUV bug?
* [x] `insert into users (id, zig, updated_at) values (5, 'wot', TIMESTAMP '2022-08-13 00:00:00'); select users.id, users.zig, users.updated_at from users;`

**Comment by deobald** [comment]
* [x] `ERROR:  DML is unsupported in a READ ONLY transaction` -- would be nice if this error multi-lines an explanation of how to get around it
* [x] basic `update` is supported according to https://github.com/xtdb/xtdb/issues/2091 but...

```
=*> update users set name='deo' where users.id=1234;
ERROR:  sql was parsed but unexpected statement encountered (report as an xtdb core2 bug)
```

* [x] should `start transaction READ WRITE;` throw a (friendly) explicit error to avoid confusion?

```
=> start transaction READ WRITE;
ERROR:  #core2.sql.parser.ParseFailure{:in "start transaction READ WRITE" ... etc ...}
LINE 1: start transaction READ WRITE;
        ^
```

* [x] should `begin READ WRITE;` throw an explicit error to avoid confusion?

```
=> begin READ WRITE;
BEGIN
=*> insert into users (id,name) values (1234,'wot');
ERROR:  DML is unsupported in a READ ONLY transaction
```

* [x] I'm not sure if this is the expected behaviour for `delete` at the moment?

```
=> set transaction READ WRITE;
=> begin;
=*> delete from users where id=1234;
_iid | _row-id | application_time_start | application_time_end
------+---------+------------------------+----------------------
(0 rows)

DELETE 0
=*> commit;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

**Comment by deobald** [comment]
* [ ] unqualified DML should warn the user: `update users set name='deo' where id=1234;` causes `Assert failed: ["XTDB requires fully-qualified columns: id at line 1, column 35"]` but the client isn't notified.
* [x] the server should recover from failed commits (`server closed the connection unexpectedly`) — this currently happens when user submits and unqualified `update`, for example, but the server should recover from this sort of exception even if unqualified DML is prevented. The cause is that the erroneous DML is still on the log when future commits are attempted. Solution is this issue: https://github.com/xtdb/xtdb/issues/2221
* [ ] `select *` error is opaque: `=> select * from users;` => `ERROR:  unexpected server error during query execution`

**Comment by refset** [comment]
- [x] error is repetitive and later caret points to wrong column number (in this example 28 is the 'A' at the start of 'ALL')
```
jdt=> start transaction read write;
DELETE FROM Prop_Owner FOR ALL APPLICATION_TIME WHERE Prop_Owner.id = 1;
commit;
BEGIN
ERROR:  Parse error at line 1, column 28:
LINE 1: DELETE FROM Prop_Owner FOR ALL APPLICATION_TIME WHERE Prop_O...
                                   ^
DETAIL:  DELETE FROM Prop_Owner FOR ALL APPLICATION_TIME WHERE Prop_Owner.id = 1
                           ^
Expected one of:
<EOF>
WHERE
PORTION
ERROR:  Parse error at line 1, column 28:
DETAIL:  DELETE FROM Prop_Owner FOR ALL APPLICATION_TIME WHERE Prop_Owner.id = 1
                           ^
Expected one of:
<EOF>
WHERE
PORTION
```
cc @deobald

**Comment by refset** [comment]
Attempting to use "60" in `TIMESTAMP '2022-09-07 21:55:60.709207'` during DML (oops!):

```
jdt=> start transaction read write;
INSERT INTO Prop_Owner (id, customer_number, property_number, application_time_start, application_time_end)
VALUES (1, 145, 7797, TIMESTAMP '1998-01-03 00:00:00', TIMESTAMP '2022-09-07 21:55:60.709207');
commit;
BEGIN
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
psql (13.6, server 14)
WARNING: psql major version 13, server major version 14.
         Some psql features might not work.
COMMIT
jdt=>
```

```
java.time.DateTimeException: Invalid value for SecondOfMinute (valid values 0 - 59): 60
	at java.base/java.time.temporal.ValueRange.checkValidValue(ValueRange.java:319)
	at java.base/java.time.temporal.ChronoField.checkValidValue(ChronoField.java:718)
	at java.base/java.time.LocalTime.of(LocalTime.java:343)
	at java.base/java.time.LocalDateTime.of(LocalDateTime.java:364)
	at core2.sql.plan$create_local_date_time.invokeStatic(plan.clj:262)
	at core2.sql.plan$create_local_date_time.invoke(plan.clj:260)
	at core2.sql.plan$expr.invokeStatic(plan.clj:288)
	at core2.sql.plan$expr.invoke(plan.clj:287)
	at core2.sql.plan$build_values_list$fn__16196$fn__16211.invoke(plan.clj:1603)
	at core2.rewrite$collect_stop.invokeStatic(rewrite.clj:617)
	at core2.rewrite$collect_stop.invoke(rewrite.clj:610)
	at core2.rewrite$collect_stop.invokeStatic(rewrite.clj:612)
	at core2.rewrite$collect_stop.invoke(rewrite.clj:610)
	at core2.sql.plan$build_values_list$fn__16196.invoke(plan.clj:1598)
	at core2.rewrite$collect_stop.invokeStatic(rewrite.clj:617)
	at core2.rewrite$collect_stop.invoke(rewrite.clj:610)
	at core2.rewrite$collect_stop.invokeStatic(rewrite.clj:612)
	at core2.rewrite$collect_stop.invoke(rewrite.clj:610)
	at core2.sql.plan$build_values_list.invokeStatic(plan.clj:1588)
	at core2.sql.plan$build_values_list.invoke(plan.clj:1585)
	at core2.sql.plan$plan.invokeStatic(plan.clj:1801)
	at core2.sql.plan$plan.invoke(plan.clj:1800)
	at core2.sql.plan$plan.invokeStatic(plan.clj:1801)
	at core2.sql.plan$plan.invoke(plan.clj:1800)
	at core2.sql.plan$plan.invokeStatic(plan.clj:1801)
	at core2.sql.plan$plan.invoke(plan.clj:1800)
	at core2.sql.plan$plan.invokeStatic(plan.clj:1801)
	at core2.sql.plan$plan.invoke(plan.clj:1800)
	at core2.sql.plan$plan.invokeStatic(plan.clj:1801)
	at core2.sql.plan$plan.invoke(plan.clj:1800)
	at core2.sql.plan$plan_query.invokeStatic(plan.clj:3127)
	at core2.sql.plan$plan_query.invoke(plan.clj:3116)
	at core2.sql$compile_query.invokeStatic(sql.clj:16)
	at core2.sql$compile_query.invoke(sql.clj:8)
	at core2.sql$compile_query.invokeStatic(sql.clj:9)
	at core2.sql$compile_query.invoke(sql.clj:8)
	at core2.pgwire$interpret_xt_query$fn__18789.invoke(pgwire.clj:366)
	at core2.pgwire$interpret_xt_query.invokeStatic(pgwire.clj:365)
	at core2.pgwire$interpret_xt_query.invoke(pgwire.clj:354)
	at core2.pgwire$interpret_sql.invokeStatic(pgwire.clj:495)
	at core2.pgwire$interpret_sql.invoke(pgwire.clj:377)
	at core2.pgwire$cmd_simple_query.invokeStatic(pgwire.clj:1762)
	at core2.pgwire$cmd_simple_query.invoke(pgwire.clj:1761)
	at core2.pgwire$conn_loop.invokeStatic(pgwire.clj:1933)
	at core2.pgwire$conn_loop.invoke(pgwire.clj:1854)
	at core2.pgwire$connect$fn__19525.invoke(pgwire.clj:1998)
	at core2.pgwire$connect.invokeStatic(pgwire.clj:1996)
	at core2.pgwire$connect.invoke(pgwire.clj:1950)
	at core2.pgwire$accept_loop$fn__19539$fn__19540$fn__19541.invoke(pgwire.clj:2071)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

cc @jarohen

**Comment by jarohen** [comment]
@refset have split that one into its own card - I suspect that if the core threw an IAE then pgwire would handle it just fine

**Comment by deobald** [comment]
Double Quotes produce a strange error: `steven=> INSERT INTO people (id, name) VALUES (1, "Floh");` results in: 

```
ERROR:  Invalid SQL query:
  - XTDB requires fully-qualified columns: "Floh" at line 1, column 42
```

**Comment by jarohen** [comment]
@deobald as discussed, this one's a valid error message, because we're expecting double-quoted `"Floh"` to be a column reference there
