### ISSUE TITLE
Explicitly disallowing syntactic structures that we don't (yet) support

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2214]
Let's comment these out in the EBNF for the time being so that a user (hopefully) gets a parser error rather than either incorrect results or an unhelpful NPE/IAE etc.

to be discussed: whether we should just implement any of these rather than disabling them

* [x] Host params (see xtdb/xtdb#2069)
* [x] Types (§6.1, see xtdb/xtdb#2070)
* [ ] Regexes (§6.28)
* [x] Array max cardinality (§6.28)
* [x] `datetime_factor.time_zone`
* [x] rows (§6.1, §7.1, §7.2 xtdb/xtdb#2080)
* [x] `WITH RECURSIVE`
* [x] `CAST (DEFAULT AS ...)` (contextually typed value expression)
* [x] `fetch_first` `WITH TIES` (§7.13, xtdb/xtdb#2089)
* [x] `target_table` `ONLY` (§14.8)
* [x] `override_clause`, `from_default` (§14.11)
* [x] `set_clause` -> `multiple_column_assignment` (§14.15)
* [x] `update_target` -> `object_column [...]` (§14.15)
