### ISSUE TITLE
SQL tooling bash

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3093]
We'd like to be able to demonstrate XTDB's power through users being able to use standard SQL tooling to access XTDB.

This could be, for example, through tools like:

* Metabase
* Tableau
* PowerBI
* AWS QuickSight

Related: we'd like users to be able to access XTDB quickly via a terminal.
This could be:

* psql
* cURL

Such tools will generally need:

* Some way of connecting to a running XTDB node
* Some way of figuring out the schema so that they can generate queries on the user's behalf.

These tools are just suggestions - there'll be some more general work to get XTDB connecting to these kinds of tools, and some tool-specific work for each individual one we decide to support (e.g. if a tool makes a certain schema query on startup).

We currently have two early-stage protocols:

* Postgres wire protocol (pgwire)
  * this currently returns JSON for everything - we'd likely want to return numeric
  * not to mention it may well be a bit stale by now.
* Arrow Flight SQL
  * this is very much at proof-of-concept level, hacked together to get the basics working
    * schema-wise, IIRC there are a few gotchas left in the codebase here
    * would require someone getting back up to speed with what's here and what's still missing.
  * in terms of not sure of the state of support for JDBC/ODBC/ADBC, or what these tools need.

Next steps:

* [x] Figure out the current state of the existing protocol implementations.
* [x] Analyse which tools can connect using which protocols, in order to make a decision about preferring one over the other, or even implementing a new driver.
* [x] Analyse what queries such tools tend to make, and what support we have for them in XTDB.

----

2024-02-27:

We'll run with just the pgwire driver for now - this gives us the best combination of tooling reach. We may later decide to revisit the Arrow Flight SQL driver, once tooling support becomes more prevalent.

* [x] #3214
* [x] #2524 
* [x] #3232
* [x] #3215
* [x] #3216
* [x] #2225
