### ISSUE TITLE
Investigate OOMKilled issue on azure benchmark

### ISSUE THREAD

**Issue by tggreene** [xtdb/crux#3769]
We've encountered this issue a number of times while attempting to run the 24hour Azure Benchmark:
- Essentially, the containers running the OLTP loop of XTDB within Auctionmark will get killed with an "OoMKilled" message from Kubernetes.
- I've collected some metrics/monitoring graphs from around the point that these nodes get killed, see my original comments **[here](https://github.com/xtdb/xtdb/issues/3478#issuecomment-2393770716)**.   

In terms of what we would expect the nodes to use within the Kubernetes benchmark:
- We set the memory reservation to 5GB on Kubernetes.
- The nodes themselves are ran within Docker files that pass a number of flags to the JVM process which _should_ constrain our memory usage. Namely:
  - 2000m of Java Heap
  - 2000m of MaxDirectMemorySize
  - 500m of MaxMetaspaceSize

Looking at some of the memory usage graphs, we do see suggestions that the child allocators _may_ be going over what they are allowed to allocated (either that, or we are tracking their memory allocation/usage incorrectly via the Gauges). Want to investigate and prevent these getting OoMKilled by Kubernetes, and ensure there isn't a wider problem in terms of XTDB's memory usage limits. 

## Memory Graphs 
Copying some examples graphs of heap/directmemory usage from a node that gets OoMKilled:
![Image](https://github.com/user-attachments/assets/cac6040f-0255-48d7-9c7d-7dd3f995d4a2)
![Image](https://github.com/user-attachments/assets/cfc5bbd2-57d6-48e2-89c2-c5498a484005)

## TODO

- [x] Ensure we have any useful logging enabled from Kubernetes.
- [x] Investigate actual memory usage/any other useful info from Kubernetes when a container is OoMKilled.
- [x] Investigate behaviour when bumping the memory reservation. 
- [x] Validate if this problem happens with a local Kubernetes run 
  - This would use local minikube for running Kubernetes, and the nodes would use local storage and kafka log.
  - If this also happens locally, suggests a wider memory usage problem.
  - UPDATE: It does not appear to happen locally with the same reservations & JVM settings - though this was only against a 6hour run.

**Comment by danmason** [comment]
@tggreene set off a run on AKS with a 6GB memory reservation rather than a 5GB one - some updates on that:
- None of the nodes have yet to be OoMKilled.
- The nodes are all now currently hanging processes (#3770).

Given that the OoMKilled usually happens first in this scenario (often quite quickly into a run), it suggests that we are going above our bounds (2GB heap, 2GB direct memory and 500Mb metadata space) and getting OoMKilled but the extra GB of memory reservation gives us some extra headroom.

We can definitely see spikes of usage of buffer memory on a lot of the nodes that get OoMKilled - especially within the BufferPool. Of particular interest in that regard is that the BufferPool childallocator is created differently to the other child allocators. I was under the impression that all of the child allocators would respect the MaxDirectMemorySize - a mechanism I believe we achieve by using a `RootAllocator` and each of the created child allocators (see the [util.clj function](https://github.com/xtdb/xtdb/blob/main/core/src/main/clojure/xtdb/util.clj#L598)) uses its' memory reservation/limit.

Looking at the code within BufferPool I did note that it's allocator does NOT use the same limits as the other ones do (see the [function to create the buffer pool child allocator](https://github.com/xtdb/xtdb/blob/main/core/src/main/clojure/xtdb/util.clj#L598)). It seems like the buffer pool child allocators have been created in a similar way for quite a while - essentially having their own separate memory limit (0)  and reservation (Max LONG value). Memory usage there seems like it _should_ be constrained by the memory cache size of the Bufferpool (set to 512MB) 

Perhaps this would lead to memory spikes that would (just about) take us over a limit of 5GB - but I'm not entirely sure. I'd be interested to see if, say, 5.2GB was enough to stop OoMKilled from occuring.

**Comment by tggreene** [comment]
Reposting (from [slack](https://juxt.slack.com/archives/G018EA25K71/p1728921401481779)):

- Is the 7B (7gb roughly) peak on jvm_buffer_memory_used on some benchmark runs worth paying attention to?
  - MappedByteBuffers derived from FileChannels should only consume as much memory as the size of the region to be mapped and should fail on creation if not enough memory is available. Essentially this means that the metric jvm_buffer_memory_used (particularly mapped memory) isn’t a smoking gun as it can’t actually allocate beyond what’s available, although it could be reducing available memory enough that we’re seeing other allocators end up trying to take more memory than is available. **EDIT 24/22/10** - the metric jvm_buffer_memory_used for the mapped pool i.e. mmaped files is an accumulation of file sizes and does **not** contribute towards the MDMS limit. Essentially memory mapped files can use unaccounted for native memory.
- Is the MaxDirectMemorySize actually doing anything for our application?
  - Yes, both Direct ByteBuffers and MappedByteBuffers count towards the MaxDirectMemorySize limit and would throw java.lang.OutOfMemoryError: Direct buffer memory which we aren’t seeing
- Are arrow’s BufferAllocators obeying this limit (MaxDirectMemorySize)?
  - No, they’re using Unsafe.allocateMemory and managing memory independently. RootAllocators have a limit argument that we’re not using so defaulting to Long.MAX_VALUE

**Comment by tggreene** [comment]
From a pairing session on 2024/10/22 with James and Tim:

summary:
1. what metrics contribute to a process getting OOM killed by k8s
   resident memory. on the JVM, this is heap + direct + native
2. what metrics cause a JVM OOM exception
   heap > Xmx, direct > MDMS. also Arrow allocator OOM.
3. whether the limits we're imposing on ourselves (allocator limit) are representative of those metrics
   not currently.
   considerations here were:
   1. include mmap'd files in the allocator limit
   2. set allocator limit at MDMS -> Arrow OOM because we mmap way more than we ever need.
   we should consider:
   1. rather than mmap'ing the whole file, mmap in chunks, count the chunks towards our limit when they're used.
   2. use Arena (more for QoL than anything else)
4. what types of allocations count towards each metric
5. when/why we make those allocations
   - indexer usage
     - direct memory: size of live block.
       not really troubling the scorers
   - compactor usage
     - mmap'd blocks
       lazily scanning these, so we don't hypothesise it'll significantly count towards RSS.
     - big temporary direct block for the output file before it's written.
       - this definitely _does_ count towards RSS.
         but in the graphs, we didn't see that take up as much as it should have (to have caused the OOM).
       - option to reduce this (dev work)
   - query usage
     - mmap'd blocks + live block (although shared, so only counts once.)
     - direct memory: derived vectors (e.g. projections, c = a + b)
   - general on-heap overhead.

**Comment by tggreene** [comment]
Discovered that memory mapped files are not accounted for by -XX:MaxDirectMemorySize (i.e. you can allocate an arbitrarily large number of them presumably up until your native memory limit). This potentially upturns the current prevailing theory that we were OOMKilled because of a massive allocation > INT_MAX.

**Comment by tggreene** [comment]
Another avenue I explored was looking at whether using arrow-memory-unsafe with a limit set for memory usage would allow us to more directly limit memory used by arrow allocators. There were two problems with this; first that when we wrap foreign allocations for memory mapped buffers we account for the full size of the file each time so we deplete this memory fairly quickly. Secondly, the accounting seemed to be off by a fair amount over several runs, hitting arrow ooms well before the limit set. It might be worth considering again if we do something differently with memory mapped files and we can determine the reason we're seeing OOMs before we should.

**Comment by tggreene** [comment]
Tried using NMT options to capture a breakdown of memory on OOMKilled:
```
+    "-XX:NativeMemoryTracking=detail", \
+    "-XX:+UnlockDiagnosticVMOptions", \
+    "-XX:+PrintNMTStatistics", \
```

Unfortunately, this won't give us a breakdown on OOMKilled, only if the JVM can exit normally.

**Comment by tggreene** [comment]
Summary so far:
- **Overall Memory Usage in the Application**
    - **JVM Memory**
        - The JVM manages memory for the application primarily in:
            - **Heap Memory**: Stores objects and class instances created during runtime. The garbage collector manages heap memory, clearing unused objects to free space.
            - **Non-Heap Memory**: Used for storing class metadata, loaded classes, and other structures needed by the JVM.
        - The heap has been around 1gb in size during typical benchmark runs, metaspace around 200mb
    - **Direct Memory (Direct ByteBuffers)**
        - Memory allocated outside the JVM’s heap to support high-performance, low-latency I/O operations.
        - Direct ByteBuffers are a source of direct memory usage as set by -XX:MaxDirectMemorySize and will throw out of memory exceptions when it exceeds this limit.
        - Our usage of Direct ByteBuffers is relatively limited
        - **Arrow Allocators**
            - Part of Apache Arrow's memory management framework
            - We can see from the example run at the top that collectively the allocators claim to be using around 2gb at peak usage
            - May use native memory for allocations > INT_MAX
    - **Native Memory**
        - Memory that is outside the JVM's managed memory (both heap and non-heap) and is allocated for resources directly used by native code.
        - **Memory Mapped Files**
            - Memory-mapped files enable the application to access file data as if it were part of memory, improving performance for certain types of data retrieval.
            - These are fully managed by the OS and don't count towards any accountancy of memory usage in our application. Having said that we're assuming that the OS is a good steward of these memory mapped files and would page data in and out of memory based on demand and memory pressure on the machine.
- **What we've found so far**
    - We expanded the memory request for the benchmark to 6400Mi and found that we had no OOMKilled pods during a 24H run suggesting that adding around a gb extra headroom was sufficient to cover the unchecked native allocations
    - Measuring the allocator pools usage of each child allocator wasn't a smoking gun as some of the largest allocations were made well before OOMKilled was issued
    - Experimenting in the REPL we found that allocations made via NettyAllocationManager follows two different implementations based on size of requested allocation; if it’s above a given limit (which defaults to INT_MAX) then it uses `unsafe/allocateMemory` otherwise defaults to netty internal memory allocation (which counts towards the same budget as direct byte buffers). This looked like a smoking gun but it seems unlikely that we make allocations above INT_MAX and there are other sources of native memory usage that we don't have control over (like memory mapped files)
    - We tried swapping out the arrow-memory implementation to arrow-memory-unsafe - this highlighted our use of wrapForeignAllocation for memory mapped files as it accounts for the total file size even though this isn't ever realised in memory by the OS. It also seemed to throw arrow OOM exceptions well below the threshold set for the root allocator, which made me uneasy about it's usage.
    - We tried adding Native Memory Tracking flags to the benchmark run to see if it gave us more details about memory mapped file usage or anything else that might be relevant but unfortunately it doesn't get a chance to run in the event of an OOMKilled
- **What's worth looking at next**
    - Reduce memory usage in Compactor [[issue here](https://github.com/xtdb/xtdb/issues/3825)](https://github.com/xtdb/xtdb/issues/3825), potentially break down the merging into steps where we can offload some data to disk.
    - (Potentially) Use Java MemorySegments and Arenas, these might offer better memory accountancy than memory mapped files
    - Better monitoring, particularly memory usage from kubernetes perspective and if possible some insight into mmap file usage

**Comment by tggreene** [comment]
Advice for running at the moment would be allow 1.5gb headroom on a node above the requested limits for heap, direct memory et al. i.e. a 6gb node with 2gb heap, 2gb direct memory and 500mb metaspace.

**Comment by tggreene** [comment]
I've got a branch for local oom replication [here](https://github.com/tggreene/xtdb/tree/local-oom-replication).

Running with auctionmark load factor 0.1 should yield an OOMKill.

**Comment by tggreene** [comment]
Local Replication for OOMKill

JVM:
```
-Xmx2000m
-XX:MaxDirectMemorySize=2000m
-XX:MaxMetaspaceSize=500m
```
Environment Vars:
```
AUCTIONMARK_DURATION: "PT3H"
AUCTIONMARK_SCALE_FACTOR: "0.1"
```

Kubenetes Resources:
```
resources:
  requests:
    memory: "5120Mi"
  limits:
    memory: "5120Mi"
```

**Comment by jarohen** [comment]
open questions: 

- [ ] understand what values we need for Xmx and netty-direct to get the current AM run stable.
- [ ] do we need to explicitly allocate direct memory to each of the sub-allocators?
- [ ] are there any areas in particular that need to better recover from OOMEs?
- [ ] are there any signals we can pass (e.g. to the compactor) when something more critical (e.g. the indexer) gets an OOME?

**Comment by jarohen** [comment]
@FiV0 could you ensure this card's reflecting the current state when you get a mo? cheers 🙏

**Comment by FiV0** [comment]
PRs that have gone in to address this issue:
- https://github.com/xtdb/xtdb/pull/3954
- https://github.com/xtdb/xtdb/pull/3948
- https://github.com/xtdb/xtdb/pull/3919

Issues that are related and not yet addressed:
- https://github.com/xtdb/xtdb/issues/3825
- https://github.com/xtdb/xtdb/issues/3845

Summarizing the current state:
- OOM kills can still happen under heavy load which in the current state will likely happen during compaction (see the unrevolved tickets above)
- OOM will still happen when many resource heavy queries are run concurrently. The new memory dashboards should help with identifying this. 
- When the system is running for a long time, I suspect that metadata files will take up more and more space. The average number of files is $$4 log_4(t)$$ where $$t$$ is the time unit at which chunks arrive. Assuming a chunk per minute this results in ~13 relevant files after 120 minutes.
