### ISSUE TITLE
Restructuring/fleshing out operations documentation

### ISSUE THREAD

**Issue by danmason** [xtdb/crux#3896]
## Overview 

Currently proposed structure:

```
Operations
- Guides
- Configuration (reference-style)
  - Overview
  - Transaction Log
    - Overview
    - Kafka
  - Storage (<- storage/overview)
  - Docker/K8s (single page)
    top-level, standalone image,
    common configuration reference
  - Healthz & Metrics
    including local Grafana setup + dashboard templates
  - Authn
  - Clojure configuration cookbook
- AWS (single page)
  - Terraform
  - Docker/k8s
  - S3 Storage
  - CloudWatch metrics (dashboard to come)
    (link to Grafana dashboards too)
- Azure (single page)
  - Terraform
  - Docker/k8s
  - Azure blob storage
  - Application Insights metrics (dashboard to come)
    (link to Grafana dashboards too)
- GCP (single page)
  - Terraform
  - Docker/k8s
  - Google Cloud Storage
```

## TODO:

**Increment 1** -  see website build [here](https://monitoring-docs.d2zcybuz6k9g4m.amplifyapp.com/)
- [x] Add basic healthz/metrics setup doc.
  - [x] Add misc links to the healthz docs. 
  - [x] Move cloud metrics config to individual pages for each cloud. 
- [x] Make storage overview a top level doc, move cloud object store docs to individual pages for each cloud. 
- [x] Rename `healhz/metrics` to `monitoring and observability`
- [x] Add grafana setup notes to `healthz/metrics`, restructure to make it a bit less about _just_ configuring the node and more about the whole story of healthz/monitoring
- [x] Structure cloud operation pages, add some info around using docker, dependen infra, link to guides where appropriate.
- [x] Add links to the cloud operation pages to various cloud services used and to our Kafka docs

Want to release the above as an initial increment on the current docs.

**Increment 2**:
- [ ] Add in docker/k8s page, top level info around setup and usage.
- [ ] Add terraform & k8s templaes to setup for all clouds, (pulling out from the guides where appropriate)
  - [ ] Update cloud operations pages with the above.

**Comment by jarohen** [comment]
NB: #3792 has also landed in recent days - @danmason see how you want to incorporate that into the above structure
