### ISSUE TITLE
Trivy security actions on the sample Kubernetes XTDB deployment

### ISSUE THREAD

**Issue by danmason** [xtdb/crux#3953]
## Overview

When `Trivy` is ran against our sample kubernetes XTDB deployment, we get a number of security actions returned of varying severities. Within this card, we would like to:
- Have some ability to actively check/run the trivy action against the XTDB sample deployment.
- Investigate & fix some of the raised security vulnerabiliies, testing any fixes against our sample kubernetes deployment.

## TODO:

- [x] Some mechanism to run trivy checks against the sample deployment k8s.
- [x] Actioning the suggested problems/fixes below.

Fixing some of the raised issues:

### `HIGH` severity
- [x]  Root file system is not read-only
  - Message: Container 'xtdb-container' of StatefulSet 'xtdb-statefulset' should set 'securityContext.readOnlyRootFilesystem' to true 

### `MEDIUM` severity
- [x] Can elevate it's own privileges
  - Message: Container 'xtdb-container' of StatefulSet 'xtdb-statefulset' should set 'securityContext.allowPrivilegeEscalation' to false
- [x] Seccomp policies are disabled
  - Message: container "xtdb-container" of statefulset "xtdb-statefulset" in "default" namespace should specify a seccomp profile

### `LOW` severity
- [x] Container capabilities must only include NET_BIND_SERVICE
  - Message: container should drop all
- [x] Runtime/Default Seccomp profile not set 
  - Message: Either Pod or Container should set 'securityContext.seccompProfile.type' to 'RuntimeDefault'
- [x] Default capabilities: some containers do not drop all 
  - Message: Container 'xtdb-container' of StatefulSet 'xtdb-statefulset' should add 'ALL' to 'securityContext.capabilities.drop'   

## Security actions we can't currently action

The following three actions we will have to leave out:
- Runs as root user [MEDIUM]
- Runs with GID <= 10000  [LOW]
- Runs with UID <= 10000 [LOW]

I believe to run as a non-root user we'd need to move where some of the files are stored within the dockerfiles, so I've left these off.

**Comment by danmason** [comment]
## Security actions we can't currently action

The following three actions we will have to leave out:
- Runs as root user [MEDIUM]
- Runs with GID <= 10000  [LOW]
- Runs with UID <= 10000 [LOW]

I believe to run as a non-root user we'd need to move where some of the files are stored within the dockerfiles, so I've left these off.
